/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResidencyRouteImport } from './routes/residency'
import { Route as MatchmakerRouteImport } from './routes/matchmaker'
import { Route as ListPropertyRouteImport } from './routes/list-property'
import { Route as InvestRouteImport } from './routes/invest'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertyIdRouteImport } from './routes/property.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidencyRoute = ResidencyRouteImport.update({
  id: '/residency',
  path: '/residency',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchmakerRoute = MatchmakerRouteImport.update({
  id: '/matchmaker',
  path: '/matchmaker',
  getParentRoute: () => rootRouteImport,
} as any)
const ListPropertyRoute = ListPropertyRouteImport.update({
  id: '/list-property',
  path: '/list-property',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestRoute = InvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/invest': typeof InvestRoute
  '/list-property': typeof ListPropertyRoute
  '/matchmaker': typeof MatchmakerRoute
  '/residency': typeof ResidencyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/invest': typeof InvestRoute
  '/list-property': typeof ListPropertyRoute
  '/matchmaker': typeof MatchmakerRoute
  '/residency': typeof ResidencyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/invest': typeof InvestRoute
  '/list-property': typeof ListPropertyRoute
  '/matchmaker': typeof MatchmakerRoute
  '/residency': typeof ResidencyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/calculator'
    | '/contact'
    | '/dashboard'
    | '/how-it-works'
    | '/invest'
    | '/list-property'
    | '/matchmaker'
    | '/residency'
    | '/sitemap.xml'
    | '/property/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/calculator'
    | '/contact'
    | '/dashboard'
    | '/how-it-works'
    | '/invest'
    | '/list-property'
    | '/matchmaker'
    | '/residency'
    | '/sitemap.xml'
    | '/property/$id'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/calculator'
    | '/contact'
    | '/dashboard'
    | '/how-it-works'
    | '/invest'
    | '/list-property'
    | '/matchmaker'
    | '/residency'
    | '/sitemap.xml'
    | '/property/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  CalculatorRoute: typeof CalculatorRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  HowItWorksRoute: typeof HowItWorksRoute
  InvestRoute: typeof InvestRoute
  ListPropertyRoute: typeof ListPropertyRoute
  MatchmakerRoute: typeof MatchmakerRoute
  ResidencyRoute: typeof ResidencyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PropertyIdRoute: typeof PropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residency': {
      id: '/residency'
      path: '/residency'
      fullPath: '/residency'
      preLoaderRoute: typeof ResidencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchmaker': {
      id: '/matchmaker'
      path: '/matchmaker'
      fullPath: '/matchmaker'
      preLoaderRoute: typeof MatchmakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-property': {
      id: '/list-property'
      path: '/list-property'
      fullPath: '/list-property'
      preLoaderRoute: typeof ListPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest': {
      id: '/invest'
      path: '/invest'
      fullPath: '/invest'
      preLoaderRoute: typeof InvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  CalculatorRoute: CalculatorRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  HowItWorksRoute: HowItWorksRoute,
  InvestRoute: InvestRoute,
  ListPropertyRoute: ListPropertyRoute,
  MatchmakerRoute: MatchmakerRoute,
  ResidencyRoute: ResidencyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PropertyIdRoute: PropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
